name: Déploiement Material for MkDocs sur GitHub Pages (avec uv)

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurer les informations d'identification Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Configuration de Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Installation de uv
        run: pip install uv

      - name: Créer l'environnement virtuel
        run: uv venv

      - name: Activer l'environnement virtuel
        run: source .venv/bin/activate

      - name: Calcul de l'ID du cache
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - name: Cache des dépendances uv
        uses: actions/cache@v4
        with:
          key: uv-cache-${{ env.cache_id }}-${{ hashFiles('uv.lock') }}
          path: .venv  # Chemin vers l'environnement virtuel
          restore-keys: |
            uv-cache-

      - name: Installer les dépendances avec uv
        run: uv sync  # Ou uv pip install mkdocs-material si pas de uv.lock

      - name: Déploiement du site
        run: uv run mkdocs gh-deploy --force
